### ISSUE TITLE
Time-dependent testings and scheduling

### ISSUE THREAD

**Issue by QuentinRoy** [cartant/rxjs-marbles#24]
Though the library does make user of rxjs' scheduler internally, it isn't directly expose nor documented. 

I needed marble testing for some time-dependent observable (namely, I am using `debounceTime`). I had to dig in the code source of the library, the code source of RxJs and read some stuff to understand how was time management dealt with and finally realize that because `rxjs-marbles` is really just a wrapper around the stuffs in `rxjs/testing`, I could have access to the scheduler being used through the `scheduler` property of one of my observables.

It solved my issue but by looking at the source code of `context`, it is not super clear how is `rxjs-marbles` manages schedulers: it seems it could recreate a new at some point though I am not really sure when, and it seems `Context` deliberately keeps its scheduler private.

If directly accessing an observable's `scheduler` member is safe, I believe it is probably useful to document so that other users do not have to go through the same trouble I had too (I believe time-dependent testing is not rare).
If that is possible, it would also be nice if the scheduler could be exposed by context. Accessing it through the observables is clearly hacky.

**Comment by cartant** [comment]
The `Context` does expose the `TestScheduler` as a property. And the `Context` interface that's included in the [README](https://github.com/cartant/rxjs-marbles#marbles) lists `scheduler` as a public, read-only property:

```ts
readonly scheduler: TestScheduler;
```

Perhaps you missed it in the source because it's a property that's declared [via the constructor](https://github.com/cartant/rxjs-marbles/blob/v2.3.1/source/context.ts#L31)?

```ts
constructor(public readonly scheduler: TestScheduler) {}
```

The Usage section of the README has grown substantially over time. I guess I should restructure the READ and split it into several files, so users of the package don't have to scroll past examples for test frameworks that they might not be using before they get to the API section of the README.

**Comment by QuentinRoy** [comment]
Oh. Yes I missed it. And I don't think I understood at the time I read the readme that context is the object provided to the test handler, but it is more than likely that I read it a bit too fast
Also I do not know typescript so it doesn't help.
Thank you for your answer. I am closing the issue.
