### ISSUE TITLE
Support for rendering marble diagrams

### ISSUE THREAD

**Issue by codemile** [cartant/rxjs-marbles#64]
Is it possible to render diagrams for documentation using this library?

Rxjs has a diagram render. Is it compatible with this library?

https://github.com/ReactiveX/rxjs/blob/ffb4b0b52f8f8402ddd354169be285c78fcf9988/spec/operators/audit-spec.ts#L10

**Comment by cartant** [comment]
Nope. When I created this package, both the marble testing and the diagram generation were RxJS internals, but I felt the diagram generation was 'more internal' and didn't want this package to touch that stuff. Since then, marble testing has been exposed as a public API (and this package is now a pretty thin wrapper around that API).

I know that Martin Sikora pulled did something with the diagram generation business in his `rxjs-extra` package - see [the testing docs](https://github.com/martinsik/rxjs-extra#testing) - so maybe you could use that as a reference?

Anyway, the short answer is 'no'.

**Comment by codemile** [comment]
Thanks for the quick response. I'll take a look at how he implement the diagrams.
